platform :ios, '9.0'
use_frameworks!

def testing_pods
    pod 'Quick', '~> 0.9.2'
    pod 'Nimble', '~>4.0.0'
end

target 'SwiftTicTacToeTests' do
    testing_pods
end

target 'SwiftTicTacToeUITests' do
    testing_pods
end