platform :ios, '9.0'
use_frameworks!

def testing_pods
    pod 'Quick', '~> 0.6.0'
    pod 'Nimble', '2.0.0-rc.3'
end

target 'SwiftTicTacToeTests' do
    testing_pods
end

target 'SwiftTicTacToeUITests' do
    testing_pods
end